Ajout d'une colonne "Gagnant"
TableauBits/Mellotron pull request #47
Opened 2022-07-15 02:44 UTC by hvdbm

## Description

### :rocket: Nouveauté
* Ajout d'une colonne affichant si une chanson a gagné une constitution.

### :bug: Bugfix
* Correction de certaines données.

### :hammer_and_wrench: Refactoring
* Ajout d'une propriété "version" dans le Local Storage afin de pas briser le storage d'un utilisateur si jamais les valeurs sauvegardés ne correspondent pas et de le réinitialiser au besoin.

## Dépendance issues/pull request

* Close #39 

## Checklist

À être vérifié par les reviewers: 
- [ ] La PR a un bon titre
- [ ] Les labels sont bien attribués
- [ ] Les champs de la PR sont correctement remplis

2022-07-19 21:08 UTC, Ithyx requested changes

2022-07-19 21:08 UTC, Ithyx commented on src/app/components/table-viewer/table-viewer.component.html
> +                                Win
Pourquoi en anglais alors que les autres colonnes sont en français ?

2022-07-22 09:46 UTC, hvdbm commented on src/app/components/table-viewer/table-viewer.component.html
> +                                Win
Oups 🤦

2022-07-22 09:52 UTC, hvdbm commented on src/app/components/table-viewer/table-viewer.component.html
> +                                Win
J'avais déjà fait la correction mais j'avais oublié de push

2022-07-22 12:40 UTC, rakruk approved these changes

2022-07-22 22:09 UTC, hvdbm commented
Puisque que j'ai fait les corrections de https://github.com/TableauBits/Mellotron/pull/47#discussion_r924957074 et que @rakruk a validé, je merge

2022-07-22 22:09 UTC, merged