diacritics insensitive search
TableauBits/Mellotron pull request #66
Opened 2024-01-23 23:54 UTC by rakruk

## Description
Recherche indépendante des accents

### :rocket: Nouveauté
Avant:
![image](https://github.com/TableauBits/Mellotron/assets/43119833/0df32065-049a-409b-ac83-3e5d77f780d1)

Après:
![image](https://github.com/TableauBits/Mellotron/assets/43119833/a0cd4fa6-b2f6-4191-ab9f-e669d96c0be6)

## Checklist

À être vérifié par les reviewers: 
- [x] La PR a un bon titre
- [x] Les labels sont bien attribués
- [x] Les champs de la PR sont correctement remplis

2024-01-24 00:15 UTC, hvdbm requested changes
Est-ce qu'on voudrait ajouter une option pour activer/désactiver cette feature ? En fonction de la langue ça peut avoir de l'importance (ex : français et portugais). Après, on a que 2109 lignes donc le nombre de faux-positifs devrait pas être titanesque.

2024-01-24 00:15 UTC, hvdbm commented on src/app/constants/table.ts
> +    transformedFilter = transformedFilter.normalize("NFD").replace(/[\u0300-\u036f]/g, "");
Peut-être ?

```suggestion
    const transformedFilter = filter.trim()
                               .toLowerCase()
                               .normalize("NFD")
                               .replace(/[\u0300-\u036f]/g, "");
```

2024-01-24 00:15 UTC, hvdbm commented on src/app/constants/table.ts
> +    dataStr = dataStr.normalize("NFD").replace(/[\u0300-\u036f]/g, "");
Même chose pour `dataStr` où les actions de `normalize` et `replace` peuvent être directement faite après le `toLowerCase` à la ligne 32.

2024-01-24 19:35 UTC, rakruk commented
> Après, on a que 2109 lignes donc le nombre de faux-positifs devrait pas être titanesque.
Effectivement. J'attendrai qu'on ai des retours avant d'implémenter un toggle.

2024-01-25 00:04 UTC, hvdbm approved these changes

2024-01-25 01:13 UTC, merged